apiVersion: v1
kind: Service
metadata:
  name: heart-mlops-service
spec:
  type: NodePort
  selector:
    app: heart-mlops
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30007
